file_format: "2"
id: corne
name: Corne
type: shield
url: https://github.com/tannakartikey/zmk-config
requires: [seeeduino_xiao_ble]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - studio
siblings:
  - corny_left
  - corny_right
